### ISSUE TITLE
Application template

### ISSUE THREAD

**Issue by Seaborg** [samvera-deprecated/curate#501] opened 2014-04-15 14:48 UTC
rails new my_curate_application -m https://raw.github.com/projecthydra/curate/master/lib/generators/curate/application_template.rb

throws:
The template [https://raw.github.com/projecthydra/curate/master/lib/generators/curate/application_template.rb] could not be loaded. Error: Could not find "predicate_mappings.yml" in any of your source paths.

**Comment by jcoyne** [comment] 2014-04-15 17:50
Duplicate of #500

**Closed as completed by jcoyne** 2014-04-15 17:50 UTC
